controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController



position_controller:
    ros__parameters:
        joints:
            - lefthingefront
            - righthingefront
            - link_joint_1
            - link_joint_2
            - link_joint_3
            - link_joint_4
            - link_joint_5
            - link_joint_6
        pid:
          gains:
            link_joint_1: {p: 100.0, i: 0.01, d: 20.0}
            link_joint_2: {p: 200.0, i: 0.02, d: 40.0}
            link_joint_3: {p: 150.0, i: 0.03, d: 30.0}
            link_joint_4: {p: 100.0, i: 0.01, d: 20.0}
            link_joint_5: {p: 500.0, i: 0.005, d: 10.0}
            link_joint_6: {p: 200.0, i: 0.002, d: 5.0}
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity


velocity_controller:
    ros__parameters:
        joints:
            - leftwheelfront
            - rightwheelfront
            - leftwheelback
            - rightwheelback
            - link_joint_1
            - link_joint_2
            - link_joint_3
            - link_joint_4
            - link_joint_5
            - link_joint_6
        pid:
          gains:
            leftwheelfront: {p: 100.0, i: 0.0, d: 0.0}
            rightwheelfront: {p: 100.0, i: 0.0, d: 0.0}
            leftwheelback: {p: 100.0, i: 0.0, d: 0.0}
            rightwheelback: {p: 100.0, i: 0.0, d: 0.0}
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity
