controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController



position_controller:
    ros__parameters:
        joints:
            - lefthingefront
            - righthingefront
            - link_joint_1
            - link_joint_2
            - link_joint_3
            - link_joint_4
            - link_joint_5
            - link_joint_6
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity


velocity_controller:
    ros__parameters:
        joints:
            - leftwheelfront
            - rightwheelfront
            - leftwheelback
            - rightwheelback
            - link_joint_1
            - link_joint_2
            - link_joint_3
            - link_joint_4
            - link_joint_5
            - link_joint_6
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity
